/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_gerardodiaz;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gerar
 */
public class MainLab8 extends javax.swing.JFrame {
    Items it = new Items();
    int dinero = 200;
    int banco = 0;
    /**
     * Creates new form MainLab8
     */
    public MainLab8() {
        initComponents();
        AV = new administrarVida(pg_c, ff_vida, ff_delay);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BT_Alimento = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        pg_c = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombreMAS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ff_vida = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        ff_delay = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        ff_costo = new javax.swing.JFormattedTextField();
        jb_color = new javax.swing.JButton();
        jb_crearITEM = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rb_si = new javax.swing.JRadioButton();
        rb_no = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ff_probabilidadOBT = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        ff_Precio = new javax.swing.JFormattedTextField();
        jb_crearMAS = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_nombreZONA = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ff_probDERRUMBE = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        ff_probATA = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_items = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jb_crearZONA = new javax.swing.JButton();
        tf_nombreITEM = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_personas = new javax.swing.JList();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_comandos = new javax.swing.JTextArea();
        tf_valid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Delay", "Costo", "Color", "Puntos De Vida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabla1);

        pg_c.setMaximum(50);
        pg_c.setValue(50);
        pg_c.setStringPainted(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
                    .addComponent(pg_c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pg_c, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mascota", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Crear Mascota");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Puntos de Vida");

        try {
            ff_vida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Delay");

        ff_delay.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        ff_delay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ff_delayActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Costo");

        ff_costo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jb_color.setText("Color");
        jb_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_colorMouseClicked(evt);
            }
        });

        jb_crearITEM.setText("Crear Item");
        jb_crearITEM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearITEMMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jb_crearITEMMouseEntered(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Crear Item");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre");

        BT_Alimento.add(rb_si);
        rb_si.setForeground(new java.awt.Color(255, 255, 255));
        rb_si.setText("SI");

        BT_Alimento.add(rb_no);
        rb_no.setForeground(new java.awt.Color(255, 255, 255));
        rb_no.setText("NO");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Es Alimento?");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Probabilidad de Obtencion");

        try {
            ff_probabilidadOBT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ff_probabilidadOBT.setDoubleBuffered(true);
        ff_probabilidadOBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ff_probabilidadOBTActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Precio de Venta");

        ff_Precio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jb_crearMAS.setText("Crear Mascota");
        jb_crearMAS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearMASMouseClicked(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Crear Zona");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nombre");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Probabilidad de Derrumbe");

        try {
            ff_probDERRUMBE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Probalidad de Ataque");

        try {
            ff_probATA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Agregar Item");

        ta_items.setBackground(new java.awt.Color(153, 153, 153));
        ta_items.setColumns(20);
        ta_items.setRows(5);
        jScrollPane2.setViewportView(ta_items);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Items");

        jb_crearZONA.setText("Crear Zona");
        jb_crearZONA.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jb_crearZONAMouseDragged(evt);
            }
        });
        jb_crearZONA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearZONAMouseClicked(evt);
            }
        });

        jl_personas.setBackground(new java.awt.Color(153, 153, 153));
        jl_personas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jl_personas.setForeground(new java.awt.Color(153, 255, 51));
        jl_personas.setModel(new DefaultListModel());
        jl_personas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_personasMouseClicked(evt);
            }
        });
        jl_personas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jl_personasKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(jl_personas);

        jLabel17.setText("Key Pressesed \"Delete\" para eliminar");

        jLabel18.setText("Key Pressesed \"enter\" para agregar al Items");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jb_crearMAS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jb_color, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ff_delay)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ff_costo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ff_vida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nombreMAS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(98, 98, 98)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ff_Precio)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jb_crearITEM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ff_probabilidadOBT)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(rb_si, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rb_no)))
                            .addComponent(tf_nombreITEM, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ff_probATA, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(ff_probDERRUMBE, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_nombreZONA, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_crearZONA, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ff_probDERRUMBE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rb_si)
                                    .addComponent(rb_no))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel9)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_nombreMAS, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_nombreZONA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(tf_nombreITEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ff_probATA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jb_crearZONA))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ff_probabilidadOBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(jb_crearITEM, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ff_vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(ff_delay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ff_costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ff_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)
                                .addComponent(jb_color, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jb_crearMAS, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Administracion", jPanel2);

        ta_comandos.setColumns(20);
        ta_comandos.setRows(5);
        jScrollPane1.setViewportView(ta_comandos);

        tf_valid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tf_valid.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_valid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_validKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE)
                    .addComponent(tf_valid))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_valid, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Comandos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ff_delayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ff_delayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ff_delayActionPerformed

    private void ff_probabilidadOBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ff_probabilidadOBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ff_probabilidadOBTActionPerformed

    private void jb_colorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_colorMouseClicked
        // TODO add your handling code here:
        
        jb_color.setBackground(
                    JColorChooser.showDialog(this, "Selecione un color", Color.yellow)
        );
        
    }//GEN-LAST:event_jb_colorMouseClicked

    private void jb_crearMASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearMASMouseClicked
        // TODO add your handling code here:
        Mascotas mas = new Mascotas();
        
        String nombre;
        int vida, delay, costo;
        Color colo;
        
       nombre = tf_nombreMAS.getText();
       mas.setNombreMAS(nombre);
       vida = Integer.parseInt(ff_vida.getText());
       mas.setVida(vida);
       delay = Integer.parseInt(ff_delay.getText());
       mas.setDelay(delay);
       costo = Integer.parseInt(ff_costo.getText());
       mas.setCosto(costo);
       colo = jb_color.getBackground();
       mas.setColor(colo);
       
       Mascotas mascota  = new Mascotas(nombre, vida, delay, costo, colo);
       mascotas.add(mascota);
       administrarMascotas ap = new administrarMascotas("./Mascotas.cbm");
        ap.cargarArchivo();  
        ap.escribirArchivo();
        JOptionPane.showMessageDialog(this,
                "Mascota guardada exitosamente");
       
       tf_nombreMAS.setText("");
       ff_vida.setText("");
       ff_delay.setText("");
       ff_costo.setText("");
       jb_color.setBackground(Color.WHITE);
       
       
       
    }//GEN-LAST:event_jb_crearMASMouseClicked

    private void jb_crearITEMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearITEMMouseClicked
        // TODO add your handling code here:
        
        String nombre, alimento;
        int prob, precio;
        
        nombre = tf_nombreITEM.getText();
        
        
        if(rb_si.isSelected()){
            alimento = "si";
            it.setAlimento(nombre);
        }else{
            alimento = "no";
            it.setAlimento(" ");
            
        }
        
        if(rb_no.isSelected()){
            alimento = "no";
            it.setAlimento(alimento);
            it.setAlimento(" ");
        }else{
            alimento = "si";
            it.setAlimento(nombre);
        }
        
        prob = Integer.parseInt(ff_probabilidadOBT.getText());
        it.setProbOBT(prob);
        precio = Integer.parseInt(ff_Precio.getText());
        it.setPrecio(precio);
        
        Items its = new Items(nombre, alimento, prob, precio);
        items.add(its);
        DefaultListModel modelo
                = (DefaultListModel) jl_personas.getModel();

        modelo.addElement(new Items(tf_nombreITEM.getText(), 
                tf_nombreITEM.getText(),
                Integer.parseInt(ff_probabilidadOBT.getText()), 
                Integer.parseInt(ff_Precio.getText())));
        
        administrarItems ap = new administrarItems("./Items.cbm");
        ap.cargarArchivo();  
        ap.escribirArchivo();
        administrarItems ap1= new administrarItems("./Items1.txt");
        ap1.cargarArchivo();  
        ap1.escribirArchivo();
        JOptionPane.showMessageDialog(this,
                "Item guardada exitosamente");
        tf_nombreITEM.setText("");
        rb_si.setSelected(false);
        rb_no.setSelected(false);
        ff_Precio.setText("");
        ff_probabilidadOBT.setText("");
        
        
    }//GEN-LAST:event_jb_crearITEMMouseClicked

    private void jb_crearZONAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearZONAMouseClicked
        // TODO add your handling code here:+
        Zona zone = new Zona();
        String nombre, renumeracion, personal;
        int probDER, probMEG;
        
        nombre = tf_nombreZONA.getText();
        zone.setNombre(nombre);
        renumeracion = tf_nombreZONA.getText();
        zone.setRenumeracion(renumeracion);
        probDER = Integer.parseInt(ff_probDERRUMBE.getText());
        zone.setProbDERRUMBE(probDER);
        probMEG= Integer.parseInt(ff_probATA.getText());
        zone.setProbMEGA(probMEG);
        personal = ta_items.getText();
        personalizado.add(personal);
        
        Zona zona =  new Zona(nombre,renumeracion, probDER, probMEG);
        zonas.add(zona);
        
        tf_nombreZONA.setText("");
        ff_probDERRUMBE.setText("");
        ff_probATA.setText("");
        ta_items.setText("");
     
    }//GEN-LAST:event_jb_crearZONAMouseClicked

    private void jb_crearZONAMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearZONAMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_crearZONAMouseDragged

    private void jb_crearITEMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearITEMMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_crearITEMMouseEntered

    private void jl_personasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_personasMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jl_personasMouseClicked

    private void jl_personasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jl_personasKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_DELETE) {
            if (jl_personas.getSelectedIndex() >= 0) {
                DefaultListModel modelo
                = (DefaultListModel) jl_personas.getModel();
                modelo.remove(jl_personas.getSelectedIndex());
                jl_personas.setModel(modelo);
                JOptionPane.showMessageDialog(this,
                    "Eliminado exitosamente");

            }
        }
        ta_items.setText("");
        if (evt.getKeyCode() == evt.VK_ENTER) {
            if (jl_personas.getSelectedIndex() >= 0) {
                DefaultListModel modelo
                        = (DefaultListModel) jl_personas.getModel();
                administrarItems ap1 = new administrarItems("./Items1.txt");
                ap1.cargarArchivo();
                for (Items t : ap1.getListaItems() ) {
                    ta_items.append(t.toString());

                }

                JOptionPane.showMessageDialog(this,
                        "Copiado exitosamente");

            }
        }
        
        
    }//GEN-LAST:event_jl_personasKeyPressed

    private void tf_validKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_validKeyPressed
        // TODO add your handling code here:
        String validaciones = tf_valid.getText();
        
        if (evt.getKeyCode() == evt.VK_ENTER) {
            
            if(validaciones.contains("!pet list")){
                petlist();
                tf_valid.setText("");
            }
            if(validaciones.contains("!pet active")){
                petactive();
                tf_valid.setText("");
            }
            if(validaciones.contains("!pet feed ")){
                petfeed();
                tf_valid.setText("");
            }
            if(validaciones.contains("!adopt ")){
                adopt();
                tf_valid.setText("");
            }
            if(validaciones.contains("!mine ")){
                mine();
                tf_valid.setText("");
            }
            if(validaciones.contains("!fish ")){
                fish();
                tf_valid.setText("");
            }
            if(validaciones.contains("!zone list ")){
                zonelist();
                tf_valid.setText("");
            }
            if(validaciones.contains("!sell  ")){
                sellitem();
                tf_valid.setText("");
            }
            if(validaciones.contains("!item list")){
                itemlist();
                tf_valid.setText("");
            }
            if(validaciones.contains("!buy ")){
                buyitem();
                tf_valid.setText("");
            }
            if(validaciones.contains("!bag ")){
                bag();
                tf_valid.setText("");
            }
            if(validaciones.contains("!d ")){
                d();
                tf_valid.setText("");
            }
            if(validaciones.contains("!w ")){
                w();
                tf_valid.setText("");
            }
            if(validaciones.contains("!b ")){
                b();
                tf_valid.setText("");
            }
            
            
            
        }
        
    }//GEN-LAST:event_tf_validKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLab8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLab8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BT_Alimento;
    private javax.swing.JFormattedTextField ff_Precio;
    private javax.swing.JFormattedTextField ff_costo;
    private javax.swing.JFormattedTextField ff_delay;
    private javax.swing.JFormattedTextField ff_probATA;
    private javax.swing.JFormattedTextField ff_probDERRUMBE;
    private javax.swing.JFormattedTextField ff_probabilidadOBT;
    private javax.swing.JFormattedTextField ff_vida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb_color;
    private javax.swing.JButton jb_crearITEM;
    private javax.swing.JButton jb_crearMAS;
    private javax.swing.JButton jb_crearZONA;
    private javax.swing.JList jl_personas;
    public javax.swing.JProgressBar pg_c;
    private javax.swing.JRadioButton rb_no;
    private javax.swing.JRadioButton rb_si;
    private javax.swing.JTextArea ta_comandos;
    private javax.swing.JTextArea ta_items;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField tf_nombreITEM;
    private javax.swing.JTextField tf_nombreMAS;
    private javax.swing.JTextField tf_nombreZONA;
    private javax.swing.JTextField tf_valid;
    // End of variables declaration//GEN-END:variables
   
    ArrayList<Mascotas> mascotas =  new ArrayList();
    ArrayList<Items> items = new ArrayList();
    ArrayList<Zona> zonas = new ArrayList();
    ArrayList<Object> personalizado = new ArrayList();
    ArrayList<Object> bolsa = new ArrayList();
    
    administrarVida AV;
    
    public void petlist(){
       
        ta_comandos.append("----------------------------+" + "\n");
        ta_comandos.append("-------Mascotas-------------" + "\n");
        for (Mascotas mascot : mascotas) {
            ta_comandos.append(mascot.getNombreMAS() + "\n");
            
        }
        ta_comandos.append("----------------------------" + "\n");        
    }
    
    public void petactive(){
        AV.setAvanzar(true);
    }
    
    public void petfeed(){
       
        ta_comandos.append("----------------------------+" + "\n");
        ta_comandos.append("-------Alimentos----------" + "\n");
        for (Items alimen : items) {
            ta_comandos.append(alimen.getAlimento() + "\n");
            
        }
        ta_comandos.append("----------------------------" + "\n");
        tf_valid.setText("");
        int comer = Integer.parseInt(tf_valid.getText());
        
        int puntos = 500;
        
        int vida = Integer.parseInt(ff_vida.getText()) + puntos;
    }
   public void adopt(){
       String nombre;
       int delay, costo, vida;
       Color color;

        nombre = tf_nombreMAS.getText();
        delay = Integer.parseInt(ff_delay.getText());
        costo = Integer.parseInt(ff_costo.getText());
        vida = Integer.parseInt(ff_vida.getText());
        color = jb_color.getBackground();
        
       Mascotas m = new Mascotas(nombre, vida, delay, costo, color);
        
         Object[] newrow = {
            m.getNombreMAS(),
            m.getDelay(),
            m.getCosto(),
            m.getColor(),
            m.getVida()
                 
        };
        DefaultTableModel modelo
                = (DefaultTableModel) tabla1.getModel();
        modelo.addRow(newrow);
        tabla1.setModel(modelo);

   }
   
   public void mine(){
       
   }
   public void fish(){
       
   }
   public void zonelist(){
       
        ta_comandos.append("----------------------------+" + "\n");
        ta_comandos.append("-------Zonas----------" + "\n");
        for (Zona zone : zonas) {
            ta_comandos.append(zone.getNombre() + "\n");
            
        }
        ta_comandos.append("----------------------------" + "\n");
   }
   
   public void sellitem(){
       tf_valid.setText("");
       String cosa =tf_valid.getText();
       
       if(items.contains(cosa)){
           bolsa.remove(cosa);
       }
       dinero = dinero + it.getPrecio();
       
   }
   
   public void itemlist(){
       ta_comandos.append("----------------------------+" + "\n");
       ta_comandos.append("-------Items----------" + "\n");
       for (Items ite : items) {
           ta_comandos.append(items.toString() + "\n");
       }
       ta_comandos.append("----------------------------" + "\n");
       
   }
   public void buyitem(){
       tf_valid.setText("");
       String cosa =tf_valid.getText();
       
       if(items.contains(cosa)){
           bolsa.add(cosa);
       }
       dinero = dinero - it.getPrecio();
       
   }
   
   public void bag(){
       ta_comandos.append("----------------------------+" + "\n");
       ta_comandos.append("-------Bag----------" + "\n");
       
           ta_comandos.append(bolsa + "\n");
       
       ta_comandos.append("----------------------------" + "\n");
   }
   
   public void d(){
       tf_valid.setText("");
       int cuanto = Integer.parseInt(tf_valid.getText());
       
       banco = banco + cuanto;
       dinero =  dinero - cuanto;
   }
   
   public void w(){
       tf_valid.setText("");
       int cuanto = Integer.parseInt(tf_valid.getText());
       
       dinero = dinero+cuanto;
       banco = banco - cuanto;
       
   }
   public void b(){
       ta_comandos.append("----------------------------+" + "\n");
       ta_comandos.append("-------Dinero----------" + "\n");
      
           ta_comandos.append("Dinero: "+ dinero + "\n");
           ta_comandos.append("Banco: "+ banco + "\n");

       
       ta_comandos.append("----------------------------" + "\n");
       
   }
   
   public void clear(){
       ta_comandos.setText("");
   }
       
    
}
